settings:
  application:
    host: 0.0.0.0
    mode: dev
    name: testApp
    port: "7089"
    readtimeout: 1
    writertimeout: 2
  database:
    dbtype: mysql
    host: 127.0.0.1
    name: book
    password: 123456
    port: 3306
    username: root
  jwt:
    secret: go-admin
    timeout: 3600
  log:
    dir: temp/logs
